### ISSUE TITLE
Publish version 1.1.0 to Nuget

### ISSUE THREAD

**Issue by muratov-m** [yurickas/Viber.Bot.NetCore#5]
Can you publish a version 1.1.0 to Nuget, please?

I need to upgrade my project to .Net 5.0

Commit
https://github.com/yurickas/Viber.Bot.NetCore/pull/4/commits/3891602a3df366ab6316cbbf698c0886d12d7438

**Comment by yurickas** [comment]
oh, sorry pal. i shall do it right now

чт, 28 янв. 2021 г. в 16:13, Maksim Muratov <notifications@github.com>:
